### ISSUE TITLE
Error when branch sticky

### ISSUE THREAD

**Issue by luistorresm** [Vauxoo/runbot#14]
I have [this](http://runbot.vauxoo.com/web#id=11351&view_type=form&model=runbot.branch&menu_id=173&action=158) branch on runbot.

If I change to sticky, and after come to the repo in the web, I have this error:
![captura de pantalla 2017-05-18 a la s 17 50 22](https://cloud.githubusercontent.com/assets/7606656/26226584/8ae93512-3bf2-11e7-8afc-c8cb71e1adae.png)

**Comment by luistorresm** [comment]
FYI @jesuszapata

**Comment by luistorresm** [comment]
cc @moylop260

**Comment by JesusZapata** [comment]
@luistorresm 
Now the branch master-saas-14 have one dummy build, the build is required to avoid the error

![image](https://cloud.githubusercontent.com/assets/1387970/26258086/29148f0e-3c91-11e7-8016-95cb1b7934b5.png)

**Comment by luistorresm** [comment]
Thanks @JesusZapata 

I close this Issue
